export default {
  name: 'name',
  description: 'description',
  //model: 'model',
  sku: 'sku',
  minimum_quantity: 'minQuantity',
  minimum: 'minQuantity',
  category: 'categories',
  categories: 'categories',
  product_category: 'categories',
  manufacturer: 'manufacturer',
  price: 'price',
  product_url: 'slug',
  link: 'slug',
  quantity: 'quantity',
  images: 'image',
  image: 'image',
  main_image: 'image',
  stock_status: 'status',
  meta_title: 'metaTitle',
  meta_description: 'metaDescription',
  meta_keywords: 'metaKeywords',
  meta_keyword: 'metaKeywords',
  date_available: 'dateAvailable',
}